# -*- encoding: utf-8 -*-

import IU_ADMIN_ANADIR_USUARIO
import IU_ADMIN_ANADIRSCRIPT
import IU_ADMIN_MAIN
import IU_ADMIN_MOSTRAR_ALUMNO_SCRIPT_AFECTADO
import IU_ADMIN_SCRIPTS
import IU_ADMIN_USUARIOS
